Added multi lingual support & upgraded pandoc. Added more book

diff --git a/pdf-from-tex b/pdf-from-tex
--- a/pdf-from-tex
+++ b/pdf-from-tex
@@ -54,8 +54,49 @@ trap popd EXIT
 
 echo -e "All operations would be performed using this directory as working directory: $(pwd)\n"
 
-if [ ! -f "$book_dir_rel_path/book-gen.tex" ]; then
-  echo -e "file does not exist: $book_dir_rel_path/book-gen.tex"
+
+if [ ! -f "$book_dir_rel_path/.config" ]; then
+  echo -e "Config file $book_dir_rel_path/.config is missing";
+  exit 1
+fi
+
+
+# Loads the configuration specific to the book. Usually contains settings like the tex template to use to use when exporting to pdf
+config_file_path=$script_dir/$book_dir_rel_path/.config
+source "$config_file_path"
+sourcing_status=$?
+
+if [ $sourcing_status != 0 ]; then
+  echo -e "\nError occurred while sourcing $config_file_path; Please fix the errors\n"
+  exit 1
+fi
+
+emphasize () {
+  echo "\e[1;33;4;44m$1\e[0m";
+}
+
+if [[ $BOOK_TYPE == "novel" ]]; then
+  template_file_name='novel-template.tex'
+  document_class='book'
+elif [[ $BOOK_TYPE == "textbook" ]]; then
+  template_file_name='textbook-template.tex'
+  document_class='book'
+elif [[ $BOOK_TYPE == "report" ]]; then
+  template_file_name='report-template.tex'
+  document_class='report'
+elif [[ $BOOK_TYPE == "article" ]]; then
+  template_file_name='article-template.tex'
+  document_class='article'
+elif [[ $BOOK_TYPE == "" ]]; then
+  echo -e "\nBOOK_TYPE not set in $(emphasize $config_file_path); Valid values are $(emphasize novel)/$(emphasize textbook)/$(emphasize report)/$(emphasize article)\n"
+  exit 1
+else
+  echo -e "\nInvalid BOOK_TYPE $(emphasize $BOOK_TYPE) specified in $(emphasize $config_file_path); Valid values are $(emphasize novel)/$(emphasize textbook)/$(emphasize report)/$(emphasize article)\n"
+  exit 1
+fi
+
+if [ ! -f "$book_dir_rel_path/$BOOK_TYPE-gen.tex" ]; then
+  echo -e "file does not exist: $book_dir_rel_path/$BOOK_TYPE-gen.tex"
   exit 1
 fi
 
@@ -72,7 +113,7 @@ lualatex \
     -halt-on-error \
     -interaction nonstopmode \
     -output-directory gen/ \
-    book-gen.tex
+    $BOOK_TYPE-gen.tex
 " > $gen_script
 
 chmod +x $gen_script
